export const products = [
  {
    id: 1,
    title: "Aceite Lira",
    price: 750,
    stock: 10,
    description: "Aceite de Girasol marca Lira X 1.5L",
    category: "cocina",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363369/lira_lkmsfj.webp",
  },
  {
    id: 2,
    title: "Mayonesa Hellmanns",
    price: 150,
    stock: 10,
    description: "Mayonesa marca Hellmann`s X 237g",
    category: "cocina",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/mayonesa_nde5bs.webp",
  },
  {
    id: 3,
    title: "Jardinera Okey",
    price: 113,
    stock: 10,
    description: "Jardinera marca Pkey X 350g",
    category: "cocina",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/okey_vfc1ym.jpg",
  },
  {
    id: 4,
    title: "Nesquik",
    price: 200,
    stock: 10,
    description: "Cacao para chocolatada marca Nesquik X 360g",
    category: "cocina",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/nesquik_pitgkz.webp",
  },
  {
    id: 5,
    title: "Yerba mate Amanda",
    price: 570,
    stock: 10,
    description: "Paquete de yerba Mate Amanda X 1Kg elaborada con palo",
    category: "cocina",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/amanda_j19vej.webp",
  },
  {
    id: 6,
    title: "Queso Cremoso La Paulina",
    price: 1600,
    stock: 10,
    description: "Queso cremoso marca La Paulina X 1Kg",
    category: "lacteos",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363369/quesocremoso_vwdrco.webp",
  },
  {
    id: 7,
    title: "Mozzarella La Paulina",
    price: 1199,
    stock: 10,
    description: "Queso Mozzarella marca La Paulina X 1Kg",
    category: "lacteos",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/mozzarella_ika1a8.webp",
  },
  {
    id: 8,
    title: "Queso Dambo La Paulina",
    price: 1350,
    stock: 10,
    description: "Queso Dambo marca La Paulina X Kg",
    category: "lacteos",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363369/quesodambo_oa99mb.webp",
  },
  {
    id: 9,
    title: "Queso Pategras La Paulina",
    price: 1600,
    stock: 10,
    description: "Queso Pategras/Sandwich marca La Paulina X Kg",
    category: "lacteos",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 10,
    title: "Queso rallado La Paulina",
    price: 449,
    stock: 10,
    description: "Queso rallado marca Sancor X 150g",
    category: "lacteos",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363369/ralladosancor_erwe3r.webp",
  },
  {
    id: 11,
    title: "Gancia",
    price: 249,
    stock: 10,
    description: "Aperitivo Lima Limon Gancia X 470ml",
    category: "bebidas",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/latagancia_aheatz.webp",
  },
  {
    id: 12,
    title: "Vodka New Style",
    price: 529,
    stock: 10,
    description: "Vodka marca New Style X l",
    category: "bebidas",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363369/vodkanewstyle_m9ldmn.webp",
  },
  {
    id: 13,
    title: "Speed",
    price: 219,
    stock: 10,
    description: "Energizante marca Speed",
    category: "bebidas",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363369/speed_hyctgz.jpg",
  },
  {
    id: 14,
    title: "Agua saborizada Levité",
    price: 317,
    stock: 10,
    description:
      "Agua saborizada marca Levité sabor: Naranja - Manzana - Pomelo",
    category: "bebidas",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/levite_zsbsfu.webp",
  },
  {
    id: 15,
    title: "Vino Malbec Cellia",
    price: 544,
    stock: 10,
    description: "Vino Malbec bodega Callia X 750ml",
    category: "bebidas",
    img: "https://res.cloudinary.com/dxf8ebmi7/image/upload/v1679363368/malbeccalia_csfm9p.webp",
  },
];
